ώZWVUVWYZ\\]ώVTSRSTVX\[\ώ\X\ZώURQQQQQRUXWYZ[U[XώVSRRRRRSVZYZ\]Y][ώWT[ZZ[[TW\[Z\\X\ZώWT[YZ[[TW\[Z\[W[XώWTSSSSSTWZYZ\[V[YώWTSSSSSTWZYZ\[UZWώWT[Z[[[TW\[Z\[SYXώWTZTWZ[TW\[Z\[PXUώWT[YYZ[TWZYZ\[QYWώWTSSSSSTWZYZ\[RYVώWTSSSSSTW\[Z\[SZXώWT[[[Z[TW\[Z\[TZWώWT[Z[VYTWZYZ\\U[YώWTZWZWYTWZYZ\ZU[XώWTYX[XYTWZYZYZV\ZώWTSSSSSTWZYXYZW\YώXUTTTTTUXZWXZ]X\ZώYWUUUUUWYVWZ]]Y[[ώ[Z[\\\UVZ]]]ZZ\ώZYZ[\TUZ]]]][Y\ώ\WZ[ZTTZ]]]]][X\ώ\Y[ZTTZ\\]]]ώ\\ώ\[ZTTZY\[\]ώ\ZTTZVX[Z[\ώZVTZVUW[YZ[ώXVZVTTVZXYZώXZVURSU[WXY
ώZVUSQRTZXYZώXUTRPQT[Z\[
ώWSRSQSU[X[YώVRPRRTV\Z\[	ώUSRSTVW\[ZZώ

ώVTSTUWX]\[Zώώιώ
WUTUVXY]]\[ώώνλμηώ	XWUVWYZZ]]\ώνλθικμθώYXWXYZYXZ[]ώνλθηθικκιμιώZYXYZXUWXZ[μκθηθικλλκικμώ[ZYZXTRTUW[λιικλλκιικμώ
\[Z[ZUTUWY[μλκιθθικμώUW\ZYWWY[ZλιθικλμώWY\\ZYY[Z[μλμνώ\\[\ZZZ[ώ\ZY[\ώ\Z\ÿ