þIþ+GþGþGþKIHþGþHþJGþ
JIGIJGþ
IþKHþGHJKþKIGþJJþJIþKþIGþ[ZZZ[þJþIGþ[ZYXXXYZ[þIþKþJþKJKZYXWVVVWXYZþJGþJþIþKK[YXWVVVVVWXY[KIþIGþIKþIþJK\ZXWVVVVVVVWXZ\JþHþJIGIK[YWWWVWVVUWVWY[HþIþJIKþJ[Z[\ZXWWXWVVVXYWWXZIGIþHIJK[YXZ[YXWXWXXWVVXWWYZJGþIHJ[YXWYZYYVWXYVVWVVWXZ[KIþIHGKZXVVXZYZYWYZXUVVVXY[\KJþIFGI[YWVWX[ZYXYZ\ZXWWXYZ\\JIþKHGHJZXVWXZ[[ZYXX[[YXXZ[\\\IGþJFGIKYWXYZ[[\[ZYZX[ZYZ\\[\]GIþJHGK\XVWZYWUTTUVYZYXYZ[[Z[KGJþKHEI[WVZXUVUTTUWXWYZZ[\ZXZJHþIGJZXZXVWYXVVWXYVW[[\[YXZIIþKIKZYXVXZ[ZXVXYYWVX[\ZXW[GJþK[ZYWZ\\[XUYZ[[YWVXZYWX\HþZZZ[\\[XWX[\\\[XVUWZXYKJþGþYXZ\\[YWY\JKLL\ZWVTWY[Jþ[XW\\[ZZ[\[XIHKL\ZXVVX\þ	ZVXG[XWXZ[\[FJHKZ\YXWZþ	[YWYþZUUWXZ\YGEVWYZ\ZZþ
ZXXZþ\VTVYY[XGGWXXY[\\þ
ZWWXY[XTTVYZYHGVWXY[[\[þ	[XVWX[YTVYZ[ZIHXXYZ[\[ZXZ[\þYWV[X[YYZ[[[JIYZZ[[ZXWVUUV\[[þ[XWKK\[Z[[\þKJ\[[\\[YWVUTSW\[þ[XYKJ\[[Z[[KKK[\\\[ZYXWUVX[þZXYKJ[[ZZ[KLLL\\[\\[[ZZ[[[[þHIZY[I[ZZXZKJJKJIGJJJþ
JIþ[YKZYZV[IHGGGIJþJXXYUXJIHHIJþIþWVXVW[þJJþXVWXVYþYXWZVXþYXþXZÿ